"""XEdDSA: Ed25519 signatures using Curve25519 keys.

Signal's scheme (https://signal.org/docs/specifications/xeddsa/) — WhatsApp
uses it for server certificate chain verification and for pairing-time
identity signatures.

We only need **verify** in this codebase (certificate checks, ADV signatures
generated by the phone). Signing is exclusively the phone's / server's job.
"""

from __future__ import annotations

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

P = (1 << 255) - 19  # Curve25519 field prime


def _mont_x_to_ed_y(mont_x_bytes: bytes) -> int:
    """Convert a Curve25519 Montgomery x-coordinate (32 LE bytes) to an
    Ed25519 Edwards y-coordinate (integer mod p).

    Formula: ed_y = (mont_x - 1) / (mont_x + 1)  mod p
    The high bit of mont_x_bytes[31] is cleared before conversion.
    """
    b = bytearray(mont_x_bytes)
    b[31] &= 0x7F  # Ed25519 uses the high bit as a sign bit; Curve25519 ignores it
    mont_x = int.from_bytes(b, "little") % P
    inv = pow((mont_x + 1) % P, -1, P)
    return ((mont_x - 1) * inv) % P


def verify(curve25519_pub: bytes, message: bytes, signature: bytes) -> bool:
    """Verify an XEdDSA signature under a 32-byte Curve25519 public key.

    The sign bit lives in ``signature[63]`` top bit; move it back into the
    derived Ed25519 public key before delegating to a real Ed25519 verify.
    """
    if len(curve25519_pub) != 32 or len(signature) != 64:
        return False

    ed_y = _mont_x_to_ed_y(curve25519_pub)
    ed_y_bytes = bytearray(ed_y.to_bytes(32, "little"))

    sig = bytearray(signature)
    # Recover sign bit: move signature[63][7] → ed_y_bytes[31][7], then clear.
    ed_y_bytes[31] |= sig[63] & 0x80
    sig[63] &= 0x7F

    try:
        Ed25519PublicKey.from_public_bytes(bytes(ed_y_bytes)).verify(
            bytes(sig), message
        )
        return True
    except InvalidSignature:
        return False
    except Exception:
        return False
